# Generated by Django 4.2.3 on 2023-08-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0003_advert_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='image',
            field=models.ImageField(default=1, upload_to='adverts/', verbose_name='Изображения'),
            preserve_default=False,
        ),
    ]
